name: Auto-Share Medium to LinkedIn

on:
  schedule:
    - cron: '0 */6 * * *'      # every 6 hours at minute 0
  workflow_dispatch:           # also allow manual run

jobs:
  share:
    runs-on: ubuntu-latest

    steps:
      # 1. Restore last.txt from cache (if it exists)
      - name: Restore last.txt from cache
        uses: actions/cache@v3
        with:
          path: last.txt
          key: last-txt-cache

      # 2. Check out your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 3. Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. Install dependencies
      - name: Install dependencies
        run: pip install feedparser requests

      # 5. Run the sharing script
      - name: Run share.py
        env:
          MEDIUM_RSS_URL:        ${{ secrets.MEDIUM_RSS_URL }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_ACTOR_URN:    ${{ secrets.LINKEDIN_ACTOR_URN }}
        run: python share.py

      # 6. Save last.txt back into cache
      - name: Save last.txt to cache
        uses: actions/cache@v3
        with:
          path: last.txt
          key: last-txt-cache
